sudo: false
dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
    - dbus-x11
    - libdbus-glib-1-dev
install:
  - sed -i "s|not getvar('Py_ENABLE_SHARED')|True|" $(which python)-config || true
  - pip install cryptography dbus-python
before_script:
  - git clone git://git.gnome.org/libsecret.git
script:
  - dbus-launch --exit-with-session python tests/run_tests.py libsecret/libsecret/mock-service-normal.py
  - dbus-launch --exit-with-session python tests/run_tests.py libsecret/libsecret/mock-service-only-plain.py
